name: Poify/Unpoify
on:
  push:
    branches:
        - master
    paths:
      - "ascension/lang/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Poify/Unpoify
        uses: BGforgeNet/msg2po@master
        with:
          poify: true
          unpoify: true
          push: true
